name: Lint
on: [push, pull_request]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@v2
        with:
          scandir: "./"

  pssa:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        run: Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
        shell: pwsh
      - name: Analyze
        run: Invoke-ScriptAnalyzer -Path . -Recurse -EnableExit
        shell: pwsh
